import type { EarPoint } from "./types";

/**
 * Coordinates are in the ear_outline.svg viewBox coordinate space.
 * IMPORTANT: Ear maps differ across schools/standards. This app is for education.
 *
 * NADA: 5-point protocol (point-based).
 * GB/T: This repo ships with a small "common points" starter set. Use Admin mode
 *       to re-mark coordinates to match your textbook/standard figure.
 */

export const NADA_POINTS: EarPoint[] = [
  {
    id: "NADA_SHENMEN",
    standard: "NADA",
    zh: "神门",
    en: "Shen Men",
    category: "Calming",
    organZh: "情绪/安神（科普）",
    organEn: "Calming / emotion (educational)",
    summaryZh: "NADA 五点之一。常用于科普：放松、安神、缓解紧张。",
    summaryEn: "One of the NADA 5 points. Often taught for calming/relaxation.",
    caseZh: "例：短期压力大、睡眠差的人，课程里常把它当作“放松”入口点（仅科普）。",
    caseEn: "Example: in education, often introduced as a calming point for stress/sleep (not medical advice).",
    x: 350,
    y: 505,
  },
  {
    id: "NADA_SYMPATHETIC",
    standard: "NADA",
    zh: "交感",
    en: "Sympathetic",
    category: "Calming",
    organZh: "自主神经调节概念（科普）",
    organEn: "Autonomic balance concept (educational)",
    summaryZh: "NADA 五点之一。常用于科普：与紧张反应/放松相关。",
    summaryEn: "One of the NADA 5 points. Often taught re: autonomic balance.",
    caseZh: "例：焦虑时“心跳快/胸闷”这类主观感受，课程里会用它讲“放松反应”。",
    caseEn: "Example: used in teaching about relaxation response during anxiety sensations.",
    x: 330,
    y: 560,
  },
  {
    id: "NADA_KIDNEY",
    standard: "NADA",
    zh: "肾",
    en: "Kidney",
    category: "Organs",
    organZh: "肾（科普）",
    organEn: "Kidney (educational)",
    summaryZh: "NADA 五点之一。常用于科普：精力、应激与恢复等概念。",
    summaryEn: "One of the NADA 5 points. Often taught about resilience/recovery concepts.",
    caseZh: "例：疲劳、恢复差的教育情境里，会作为“恢复/精力”概念点讲解。",
    caseEn: "Example: introduced as a recovery/resilience concept point in fatigue education contexts.",
    x: 365,
    y: 600,
  },
  {
    id: "NADA_LIVER",
    standard: "NADA",
    zh: "肝",
    en: "Liver",
    category: "Organs",
    organZh: "肝（科普）",
    organEn: "Liver (educational)",
    summaryZh: "NADA 五点之一。常用于科普：代谢/情绪相关概念。",
    summaryEn: "One of the NADA 5 points. Often taught as metabolism/emotion concept.",
    caseZh: "例：易怒、压力大的人群教育里，会把它放在“情绪与代谢”主题中讲。",
    caseEn: "Example: used in teaching about irritability/stress themes.",
    x: 380,
    y: 565,
  },
  {
    id: "NADA_LUNG",
    standard: "NADA",
    zh: "肺",
    en: "Lung",
    category: "Organs",
    organZh: "呼吸系统（科普）",
    organEn: "Respiratory concept (educational)",
    summaryZh: "NADA 五点之一。常用于科普：呼吸、胸闷、情绪与呼吸的关系等概念。",
    summaryEn: "One of the NADA 5 points. Often taught re: breath and stress.",
    caseZh: "例：紧张时呼吸浅的人，课程里会用它引出“呼吸练习 + 放松”的讨论。",
    caseEn: "Example: teaching link between shallow breathing and stress.",
    x: 355,
    y: 470,
  },
];

// A starter "GB/T common" set.
// Replace coordinates in Admin mode to match your exact reference figure.
export const GBT_COMMON_POINTS: EarPoint[] = [
  {
    id: "GBT_SHENMEN",
    standard: "GBT",
    zh: "神门",
    en: "Shen Men",
    category: "Calming",
    organZh: "安神/情志（科普）",
    organEn: "Calming / mind (educational)",
    summaryZh: "国标体系中常用点（示意）。不同教材位置可能有轻微差异。",
    summaryEn: "Common point in GB/T-style teaching (schematic).",
    x: 350,
    y: 505,
  },
  {
    id: "GBT_JIAOGAN",
    standard: "GBT",
    zh: "交感",
    en: "Sympathetic",
    category: "Calming",
    organZh: "自主神经（科普）",
    organEn: "Autonomic nervous system (educational)",
    summaryZh: "常用于讲自主神经与放松反应（科普）。",
    summaryEn: "Often taught in relation to autonomic balance (education).",
    x: 330,
    y: 560,
  },
  {
    id: "GBT_PIZHIXIA",
    standard: "GBT",
    zh: "皮质下",
    en: "Subcortex",
    category: "Calming",
    organZh: "神经调节概念（科普）",
    organEn: "Neuro-regulation concept (educational)",
    summaryZh: "常见耳穴系统中用于神经调节概念的点位（示意）。",
    summaryEn: "Commonly shown for neuro-regulation concepts (schematic).",
    x: 300,
    y: 455,
  },
  {
    id: "GBT_NEIFENMI",
    standard: "GBT",
    zh: "内分泌",
    en: "Endocrine",
    category: "Endocrine",
    organZh: "内分泌/代谢（科普）",
    organEn: "Endocrine/metabolism (educational)",
    summaryZh: "科普：激素、代谢调节相关概念点（示意）。",
    summaryEn: "Education: hormone/metabolism concept point (schematic).",
    x: 340,
    y: 640,
  },

  // Organs (concha area)
  {
    id: "GBT_FEI",
    standard: "GBT",
    zh: "肺",
    en: "Lung",
    category: "Organs",
    organZh: "呼吸系统（科普）",
    organEn: "Respiratory (educational)",
    summaryZh: "科普：呼吸相关概念点（示意）。",
    summaryEn: "Education: respiratory concept point (schematic).",
    x: 355,
    y: 470,
  },
  {
    id: "GBT_XIN",
    standard: "GBT",
    zh: "心",
    en: "Heart",
    category: "Organs",
    organZh: "心血管（科普）",
    organEn: "Cardiovascular (educational)",
    summaryZh: "科普：心血管相关概念点（示意）。",
    summaryEn: "Education: cardiovascular concept point (schematic).",
    x: 340,
    y: 495,
  },
  {
    id: "GBT_WEI",
    standard: "GBT",
    zh: "胃",
    en: "Stomach",
    category: "Organs",
    organZh: "消化系统（科普）",
    organEn: "Digestion (educational)",
    summaryZh: "科普：消化相关概念点（示意）。",
    summaryEn: "Education: digestion concept point (schematic).",
    x: 385,
    y: 505,
  },
  {
    id: "GBT_PI",
    standard: "GBT",
    zh: "脾",
    en: "Spleen (TCM)",
    category: "Organs",
    organZh: "脾（中医）/运化（科普）",
    organEn: "Spleen (TCM) / transformation (educational)",
    summaryZh: "科普：中医脾运化概念点（示意）。",
    summaryEn: "Education: TCM spleen concept point (schematic).",
    x: 395,
    y: 540,
  },
  {
    id: "GBT_GAN",
    standard: "GBT",
    zh: "肝",
    en: "Liver",
    category: "Organs",
    organZh: "代谢/情志（科普）",
    organEn: "Metabolism/emotion (educational)",
    summaryZh: "科普：肝相关概念点（示意）。",
    summaryEn: "Education: liver concept point (schematic).",
    x: 380,
    y: 565,
  },
  {
    id: "GBT_SHEN",
    standard: "GBT",
    zh: "肾",
    en: "Kidney",
    category: "Organs",
    organZh: "泌尿/精力（科普）",
    organEn: "Urinary/vitality (educational)",
    summaryZh: "科普：肾相关概念点（示意）。",
    summaryEn: "Education: kidney concept point (schematic).",
    x: 365,
    y: 600,
  },

  // Spine concept points along antihelix (schematic)
  {
    id: "GBT_JINGZUI",
    standard: "GBT",
    zh: "颈椎",
    en: "Cervical spine",
    category: "Spine",
    organZh: "颈段脊柱（科普）",
    organEn: "Cervical spine (educational)",
    summaryZh: "科普：脊柱分段概念点（示意）。",
    summaryEn: "Education: segmented spine concept point (schematic).",
    x: 305,
    y: 360,
  },
  {
    id: "GBT_XIONGZUI",
    standard: "GBT",
    zh: "胸椎",
    en: "Thoracic spine",
    category: "Spine",
    organZh: "胸段脊柱（科普）",
    organEn: "Thoracic spine (educational)",
    summaryZh: "科普：脊柱分段概念点（示意）。",
    summaryEn: "Education: segmented spine concept point (schematic).",
    x: 318,
    y: 445,
  },
  {
    id: "GBT_YAOZUI",
    standard: "GBT",
    zh: "腰椎",
    en: "Lumbar spine",
    category: "Spine",
    organZh: "腰段脊柱（科普）",
    organEn: "Lumbar spine (educational)",
    summaryZh: "科普：脊柱分段概念点（示意）。",
    summaryEn: "Education: segmented spine concept point (schematic).",
    x: 325,
    y: 535,
  },

  // Head/Face (lobule area - schematic)
  {
    id: "GBT_YAN",
    standard: "GBT",
    zh: "眼",
    en: "Eye",
    category: "HeadFace",
    organZh: "视觉（科普）",
    organEn: "Vision (educational)",
    summaryZh: "科普：眼相关概念点（示意）。",
    summaryEn: "Education: eye concept point (schematic).",
    x: 310,
    y: 720,
  },
  {
    id: "GBT_YABI",
    standard: "GBT",
    zh: "牙",
    en: "Teeth",
    category: "HeadFace",
    organZh: "牙齿/面部（科普）",
    organEn: "Teeth/face (educational)",
    summaryZh: "科普：牙面部相关概念点（示意）。",
    summaryEn: "Education: teeth/face concept point (schematic).",
    x: 340,
    y: 760,
  },
  {
    id: "GBT_YANHOU",
    standard: "GBT",
    zh: "咽喉",
    en: "Throat",
    category: "HeadFace",
    organZh: "咽喉（科普）",
    organEn: "Throat (educational)",
    summaryZh: "科普：咽喉相关概念点（示意）。",
    summaryEn: "Education: throat concept point (schematic).",
    x: 370,
    y: 735,
  },

  // Pain / musculoskeletal (schematic)
  {
    id: "GBT_JIAN",
    standard: "GBT",
    zh: "肩",
    en: "Shoulder",
    category: "Pain",
    organZh: "肩颈疼痛概念（科普）",
    organEn: "Shoulder/neck pain concept (educational)",
    summaryZh: "科普：肌骨疼痛相关概念点（示意）。",
    summaryEn: "Education: musculoskeletal pain concept point (schematic).",
    x: 270,
    y: 520,
  },
  {
    id: "GBT_YAO",
    standard: "GBT",
    zh: "腰",
    en: "Lower back",
    category: "Pain",
    organZh: "腰痛概念（科普）",
    organEn: "Low back pain concept (educational)",
    summaryZh: "科普：腰背痛相关概念点（示意）。",
    summaryEn: "Education: low back pain concept point (schematic).",
    x: 300,
    y: 615,
  },
  {
    id: "GBT_ZUOGU",
    standard: "GBT",
    zh: "坐骨神经",
    en: "Sciatic nerve",
    category: "Pain",
    organZh: "下肢放射痛概念（科普）",
    organEn: "Sciatica concept (educational)",
    summaryZh: "科普：下肢放射痛相关概念点（示意）。",
    summaryEn: "Education: sciatica concept point (schematic).",
    x: 310,
    y: 660,
  },
];

export const ALL_POINTS: EarPoint[] = [...NADA_POINTS, ...GBT_COMMON_POINTS];
